apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - name: ssh
    port: 422
    targetPort: 422
    nodePort: 422
  - name: https
    port: 443
    targetPort: 443
    nodePort: 443
    protocol: TCP

---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-service
# spec:
#   selector:
#     app: nginx
#   type: NodePort
#   ports:
#   - name: http
#     port: 80
#     targetPort: 80
#     nodePort: 80
#     protocol: TCP
#   - name: https
#     port: 443
#     targetPort: 443
#     nodePort: 443
#     protocol: TCP
#   - name: ssh
#     port: 422
#     targetPort: 422
#     nodePort: 422
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-service
# spec:
#   selector:
#     app: nginx
#   ports:
#   - name: http
#     port: 80
#     targetPort: 80
#     protocol: TCP
#   - name: https
#     port: 443
#     targetPort: 443
#     protocol: TCP
#   - name: ssh
#     port: 422
#     targetPort: 422
#   type: LoadBalancer
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        - containerPort: 422
          name: ssh